### ISSUE TITLE
Open Bugs

### ISSUE THREAD

**Issue by TheUnknownCod3r** [TheUnknownCod3r/BO4-Lucy-Menu#1]
Any Open Bugs can be posted here, and will be addressed in time.

**Comment by TheUnknownCod3r** [comment]
MapSpecificWeaps bugged with the new script, will revert prior to update

**Comment by SirCryptic** [comment]
![image](https://user-images.githubusercontent.com/48811414/212754811-e51c226f-f3d2-468f-aad8-ee70dfcd3aa8.png)

😄 made me chuckle

**Comment by TheUnknownCod3r** [comment]
> ![image](https://user-images.githubusercontent.com/48811414/212754811-e51c226f-f3d2-468f-aad8-ee70dfcd3aa8.png)
> 
> 😄 made me chuckle

Ahha no harm meant, saw you did the same thing as I did, was a pretty simple script to use.

**Comment by TheUnknownCod3r** [comment]
New feature requests:
* No Recoil - To be looked at

**Comment by TheUnknownCod3r** [comment]
closing due to the fact I just dont use it as a valid bug tracker
