### ISSUE TITLE
Missing weapons' names

### ISSUE THREAD

**Issue by ate47** [TheUnknownCod3r/BO4-Lucy-Menu#15]
https://github.com/TheUnknownCod3r/BO4-Lucy-Menu/blob/8fb09115c8e5d1dff8f6e78258796024f5fad7de/Guns%20needed#LL1C1-L1C1 @TubBuddy 

I don't have my game in English so I can't make a PR with the names, but here are the names you wanted (+2 other missing ARs)

```
kap 45      = pistol_fullauto_t8
havelina    = sniper_damagesemi_t8
m16         = tr_damageburst_t8
peacekeeper = ar_peacekeeper_t8
echohawk    = ar_doublebarrel
an94        = ar_an94
```

**Comment by TheUnknownCod3r** [comment]
Nice, Thank you! I’ll get them added at some point this evening when I get a moment. Also, thanks for your work on the raw files, they’ve helped me out a bit :)

**Comment by TubBuddy** [comment]
Thanks! Ill add them right now! <3

**Comment by ate47** [comment]
Cool it can be useful to someone lol, I have them for years

**Comment by TubBuddy** [comment]
i do have a request? Do you have anything that have to do with cases? Qould love to jsut get alot of them and hard unlock the items?

**Comment by ate47** [comment]
I don't know anything about that, knowing I have already completed the black market on my Xbox, it wasn't really useful for me, but I don't think you can do that with a GSC script

**Comment by TheUnknownCod3r** [comment]
> I don't know anything about that, knowing I have already completed the black market on my Xbox, it wasn't really useful for me, but I don't think you can do that with a GSC script

Pretty sure this is correct, Crates are awarded in Lobby, or as a challenge award, so the only real way I could see it happening would be to spoof a contract on loop in zombies, since some of them award crates iirc, and not sure how viable that would be.

**Comment by TubBuddy** [comment]
The only way would be just a 9999 crate spoof via DLL. I know the T8 unlockall has 1337 crates, you just have to remove everything else that comes with it like skins, guns etc etc. But DLLs are not my expertise.
