### ISSUE TITLE
Unlockall not unlocking all camos

### ISSUE THREAD

**Issue by CHonkNut31** [TheUnknownCod3r/BO4-Lucy-Menu#26]
For the most part this mod works great, all of its features work as intended. However, when using the unlockall tool, the red hex redux camo doesn't unlock. This means that all mastery camos are currently locked as it seems that the camo challenge doesn't track in game. Is there something that I missed while installing the menu, or is it something that isn't possible to be modded?

https://github.com/TheUnknownCod3r/BO4-Lucy-Menu/assets/143121221/44434b2c-de70-469a-9785-b3d9642bc362

**Comment by TheUnknownCod3r** [comment]
I might have missed a challenge when I uploaded it, that’s the overkill camo correct?

**Comment by CHonkNut31** [comment]
I believe so, it is the get (x) amount of kills with (x) weapon with optics and 5 attachments.

**Comment by TheUnknownCod3r** [comment]
Yeah I’ll have to check my notes on the challenges at some point, should’ve known I’d miss one

**Comment by CHonkNut31** [comment]
Alright thanks!

**Comment by TheUnknownCod3r** [comment]
> Alright thanks!

This'll take a couple of days, Im gonna have to go through everything and work out what the hash / stringname for the challenge is again, I thought it was loadedKills but apparently not. I'll get a fix out asap.
