### ISSUE TITLE
FOV (Scale)

### ISSUE THREAD

**Issue by Markopolo784** [TheUnknownCod3r/BO4-Lucy-Menu#29]
Incredible work with this mod. Never thought it'd be possible considering how restrictive it is and the online only factor.

Not an issue, just a query! Is it possible to have an fovscale option? Never liked how close the weapons were! When I saw this was a possibility, was one of the first things I wanted to do haha. I did try replacing one the functions, specifically the HUDdisable with setClientFov(number) but was getting some errors but I was probably doing it incorrectly anyway. I believe this is normal fov anyway, correct?

Thanks again!

**Comment by TheUnknownCod3r** [comment]
Currently yes the menu runs on normal FOV, with no changes. IIRC you should just be able to do self setDvar("cg_fov", 160); and set it to 160, but you'd wanna save the value first, something like this should work I think,

    SetFOV(value)
    {
        self setDvar("cg_fov", value);
        self S("FOV Set To: "+value):
    }
    
that should work I think, add it to an IntSlider option, with max value of 160, min value of 0, default of 30 or so

**Comment by Markopolo784** [comment]
Thank you.

So I added that function and added it as an option into the menu, passing in the value of 160 but I got a crash. I put a semi colon rather than a colon above and also tried removing the second line saying the fov it's set to.

Maybe this was the wrong way of doing it. I say intSliderTest but putting the code within it also caused the same crash.

Would that be something I am doing wrong?

Thanks again.

(Context below)

Menu option I added: 
self addOpt("FOV", &SetFOV, 160);

Function:
SetFOV(value)
{
    self setDvar("cg_fov", value);
    self S("FOV Set To: "+value);
}

If I remove the two lines within SetFOV, it does not crash. Is it a case that cg_fov cannot be accessed? Doubt it?

**Comment by DoubleG17** [comment]
If anyone else is wondering how they can modify a dvar using this menu I have a solution. In functions.gsc in visual studio find the "HideGun" function and modify it to the dvar you want to change. In my case I changed the default dvar it was modifying (to hide the gun) to r_lodbiasrigid -1000 because at high FOVs the object culling is extremely noticable. This works for me without crashes. If I toggle on the "Hide gun" option in game my draw distance is increased and if I turn it off it goes back to normal.
<img width="324" alt="image" src="https://github.com/TheUnknownCod3r/BO4-Lucy-Menu/assets/130624847/9a9c48b0-6ce1-4c6a-aae2-5a3c043e8b61">

**Comment by TheUnknownCod3r** [comment]
> If anyone else is wondering how they can modify a dvar using this menu I have a solution. In functions.gsc in visual studio find the "HideGun" function and modify it to the dvar you want to change. In my case I changed the default dvar it was modifying (to hide the gun) to r_lodbiasrigid -1000 because at high FOVs the object culling is extremely noticable. This works for me without crashes. If I toggle on the "Hide gun" option in game my draw distance is increased and if I turn it off it goes back to normal. <img alt="image" width="324" src="https://private-user-images.githubusercontent.com/130624847/280170831-9a9c48b0-6ce1-4c6a-aae2-5a3c043e8b61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NjQzNzgsIm5iZiI6MTcwMTU2NDA3OCwicGF0aCI6Ii8xMzA2MjQ4NDcvMjgwMTcwODMxLTlhOWM0OGIwLTZjZTEtNGM2YS1hYWUyLTVhM2MwNDNlOGI2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMDQxMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjA0N2UzODVlYzY4ODJkOWNmMWQyODFhZGNjNGQzZjU2ZjZkY2UxZTYzOWNiY2U0NzVlODA1ODM1YTM4ODViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8Aqr90fAoJ-d3yHYAk0VGJPCkdMkk_EDs3bzGu2SPns">

This is basically the description I provided anyway, lol. This is the normal way of setting an int dvar, and has been standard in Call of duty for years. the only thing different is the shorthand code for defining the bool, which is also way more popular lately. 



> Thank you.
> 
> So I added that function and added it as an option into the menu, passing in the value of 160 but I got a crash. I put a semi colon rather than a colon above and also tried removing the second line saying the fov it's set to.
> 
> Maybe this was the wrong way of doing it. I say intSliderTest but putting the code within it also caused the same crash.
> 
> Would that be something I am doing wrong?
> 
> Thanks again.
> 
> (Context below)
> 
> Menu option I added: self addOpt("FOV", &SetFOV, 160);
> 
> Function: SetFOV(value) { self setDvar("cg_fov", value); self S("FOV Set To: "+value); }
> 
> If I remove the two lines within SetFOV, it does not crash. Is it a case that cg_fov cannot be accessed? Doubt it?

The mistake I made was including the self part, which was my bad, I wrote that reply before I went to bed. It should just be SetDvar, as the other person pointed out. Apologies, Ive been occupied with other things, so didnt have time to look into this until now.

**Comment by TheUnknownCod3r** [comment]
> If anyone else is wondering how they can modify a dvar using this menu I have a solution. In functions.gsc in visual studio find the "HideGun" function and modify it to the dvar you want to change. In my case I changed the default dvar it was modifying (to hide the gun) to r_lodbiasrigid -1000 because at high FOVs the object culling is extremely noticable. This works for me without crashes. If I toggle on the "Hide gun" option in game my draw distance is increased and if I turn it off it goes back to normal. <img alt="image" width="324" src="https://private-user-images.githubusercontent.com/130624847/280170831-9a9c48b0-6ce1-4c6a-aae2-5a3c043e8b61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTQ1NjMsIm5iZiI6MTcwNDg5NDI2MywicGF0aCI6Ii8xMzA2MjQ4NDcvMjgwMTcwODMxLTlhOWM0OGIwLTZjZTEtNGM2YS1hYWUyLTVhM2MwNDNlOGI2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQxMzQ0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzU3ZDUzMGQ4MDMwZGEwNTY2ZTRiZGFkNTU4ZDBkNTZiNjI5N2Q3MzUyZjE4NGQxNzdmNjU5ZGU3ZTEwOTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bFyMUFlZw9xsA-P-8RG8xUSPJvK-ECPKxeKXzW0lDtQ">

So to close this and confirm what works, this is how you would do it. 

add a Slider option as so below:

`self addOptIncSlider("Set FOV To: ", &SetFOV, 0,0,300,5);`

then in functions.gsc, create a function as follows:

```
SetFOV(Value)
{
    setDvar("cg_fov", Value);
    self iPrintLnBold("^4FOV Set To: ^1"+Value);
}
```
