### ISSUE TITLE
New Version of BO4

### ISSUE THREAD

**Issue by NemoHaze1137** [TheUnknownCod3r/BO4-Lucy-Menu#3]
Hey where can i change the Code of the Version so i can use the menu on the newer version of bo4

**Comment by TheUnknownCod3r** [comment]
> Hey where can i change the Code of the Version so i can use the menu on the newer version of bo4

If there’s an update (I haven’t been able to test or check anything yet), you’ll have to wait for Serious to update T7 Compiler. The menu itself should work on any version of BO4.

**Comment by NemoHaze1137** [comment]
I got that error
s_assetPool:ScriptParseTree => 00007FF6C29FBBB0
Unable to identify critical injection information. Double check your script path, and try restarting the game. Make sure you are injecting in the pregame lobby.


        [scripts/zm_common/load.gsc]: Failed to Inject (0000000000000001)

**Comment by TheUnknownCod3r** [comment]
> I got that error s_assetPool:ScriptParseTree => 00007FF6C29FBBB0 Unable to identify critical injection information. Double check your script path, and try restarting the game. Make sure you are injecting in the pregame lobby.
> 
> ```
>     [scripts/zm_common/load.gsc]: Failed to Inject (0000000000000001)
> ```

This is an error related to T7 Compiler, not the Lucy Menu. The Lucy Menu compiles just fine, but the Injection process fails, which I do not control. You'll have to open an issue on https://github.com/shiversoftdev/t7-compiler/issues and let Serious know the update broke BO4 Injection.
