### ISSUE TITLE
does this work with the project bo4 shield client

### ISSUE THREAD

**Issue by aeugurauhhr** [TheUnknownCod3r/BO4-Lucy-Menu#35]
please don't close without an answer because I'm a bit incredibly annoyed that the mod menu won't inject... I just want absolute power. I've followed the instructions exactly, carefully and correctly but when I get to the bit where "this should be it now", when I inject it comes up with errors. I also tried to inject in the pre-game lobby of zombies and still no luck - the same errors pop up.

so do I have to launch the game from Battlenet/own it in order for it to work or does it work with the shield client also?

**Comment by aeugurauhhr** [comment]
again please don't close without an answer coz that'll just make me more frustrated
if it doesn't work with the client, that's fine because I still have another solution

**Comment by TheUnknownCod3r** [comment]
> please don't close without an answer because I'm a bit incredibly annoyed that the mod menu won't inject... I just want absolute power. I've followed the instructions exactly, carefully and correctly but when I get to the bit where "this should be it now", when I inject it comes up with errors. I also tried to inject in the pre-game lobby of zombies and still no luck - the same errors pop up.
> 
> so do I have to launch the game from Battlenet/own it in order for it to work or does it work with the shield client also?

I have only ever tested this on Battle.net, never shield. I do know that [RushMod t8](https://github.com/NotNierPea/RushMod-T8) by NotNierPea works on Shield, and has a port of Lucy with extra feature support due to Shields Injector. I prefer to keep this compatible with the base game.

**Comment by aeugurauhhr** [comment]
OK that's fine, thank you for answering. I might try what you said later aswell

**Comment by TheUnknownCod3r** [comment]
Closing, Please see Rushmod-T8 for shield, will eventually port Lucy to shield as well, and have two versions, one for main game other for shield.

**Comment by TheUnknownCod3r** [comment]
in *theory*, although untested, this should now work with Shield.

**Comment by ShawnSigma** [comment]
Can confirm this works with Shield, all you have to do to make it appear in the mod list is add a metadata.json file, which you can just copy from a different mod.
Here's the one I made:
[metadata.json](https://github.com/user-attachments/files/24158727/metadata.json)

Just put that and the compiled.gscc file in the same folder and put that folder in the mods directory
