### ISSUE TITLE
Menu only showing dots on submenus

### ISSUE THREAD

**Issue by Cea0611** [TheUnknownCod3r/BO4-Lucy-Menu#37]
I tried to use this menu but whenever I try to get to the options there's only dots where the options should be, I didn't modified the code in any way followed the instructions but I got this annoying problem.
![Screenshot 2024-08-07 234513](https://github.com/user-attachments/assets/e56e8fae-781b-44ef-b01f-5ebe2e7cff7c)
![Screenshot 2024-08-07 234540](https://github.com/user-attachments/assets/46d2b6a9-c154-467a-bb6b-2d49ce564735)

Is there any way to fix this? :(

**Comment by jaydenmachado919** [comment]
im having the same issue did you find a fix?

**Comment by TheUnknownCod3r** [comment]
Its due to the menu base, which I havent changed. You sometimes just need to melee to go back, then it should pop up agin.

**Comment by Cea0611** [comment]
> Its due to the menu base, which I havent changed. You sometimes just need to melee to go back, then it should pop up again.

I've tried but nothing seems to work, I go in each submenu and go back and it's still bugged :(

**Comment by TheUnknownCod3r** [comment]
> > Its due to the menu base, which I havent changed. You sometimes just need to melee to go back, then it should pop up again.
> 
> I've tried but nothing seems to work, I go in each submenu and go back and it's still bugged :(

Can you upload a video showing it? I've just reinstalled BO4 this morning as bought a new copy, and its working fine for me, albeit with the above documented issue.

**Comment by TheUnknownCod3r** [comment]
Should be fixed in the latest commit, please let me know if you encounter it further.
