### ISSUE TITLE
Give weapon function with attachments on them

### ISSUE THREAD

**Issue by Mrotszl** [TheUnknownCod3r/BO4-Lucy-Menu#39]
Hi I was wondering if its possible to update this such that the give weapon function gives the player the weapon with all the configurated attachments on it. At the moment it only gives the weapon with nothing on it regardless of what I put on in my inventory.

Thank you!

**Comment by TheUnknownCod3r** [comment]
Looking into it, probably something to do with how I give the weapons. Sorry for the late, only just grabbed a new copy of BO4

**Comment by Mrotszl** [comment]
> Looking into it, probably something to do with how I give the weapons. Sorry for the late, only just grabbed a new copy of BO4

All good, didn't think you'd reply when I raised the question haha. 

Back in 2021 I used a paid BO4 menu (nautaprint from ItsFebiven) and it does that - give weapon function seems to just bring the version that was configured in the personal loadout as if you bought it off the wall/gotten it from the mystery box. I've lost access to the menu and have been trying to figure out how it all works ever since the Lucy menu was public. Obviously with my lack of coding skills I could not figure it out......thanks for looking into it.

**Comment by Mrotszl** [comment]
> Please try the newest push, see if that works for you. I currently don't have bo4 to test, but iirc the func is just get_weapon_with_attachments, but don't recall if that works the way im doing it

Heya, thanks for having a go! 

I had a quick try at the latest menu (compiled with T8 compiler not ran with VSC), seems to give me an error and kicks me back to the lobby again, this was on blood of the dead with 3 bots, no custom mutations. Please see attachment for screenshot of error.

![error BO4](https://github.com/user-attachments/assets/f4c01350-8c28-4694-8a10-62d8a9ce30db)

**Comment by TheUnknownCod3r** [comment]
> > Please try the newest push, see if that works for you. I currently don't have bo4 to test, but iirc the func is just get_weapon_with_attachments, but don't recall if that works the way im doing it
> 
> Heya, thanks for having a go!
> 
> I had a quick try at the latest menu (compiled with T8 compiler not ran with VSC), seems to give me an error and kicks me back to the lobby again, this was on blood of the dead with 3 bots, no custom mutations. Please see attachment for screenshot of error.
> 
> ![error BO4](https://private-user-images.githubusercontent.com/178079789/389713740-f4c01350-8c28-4694-8a10-62d8a9ce30db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NzM3ODEsIm5iZiI6MTczMjU3MzQ4MSwicGF0aCI6Ii8xNzgwNzk3ODkvMzg5NzEzNzQwLWY0YzAxMzUwLThjMjgtNDY5NC04YTEwLTYyZDhhOWNlMzBkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQyMjI0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODI4MzJiNjIwMWJiNmFjYzZhZTgzMTk0ZDgxOGEwMTRlM2FkZTkwYWZlYmQyYjY2ZTk2M2QzZGQyZWJiNjcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZWVhKIIhI8uY30dLU68iU1Qd20mbPhCp6omgV2-2Yrg)

Yep, that probably means I need to actually install a copy somehow and test it. ugh, Give me a couple more days, I'll buy it tomorrow.

**Comment by TheUnknownCod3r** [comment]
I just pushed one last thing I can try before tomorrow, you can try that I guess.

**Comment by TheUnknownCod3r** [comment]
Completed in latest push

**Comment by Mrotszl** [comment]
> Completed in latest push

Thanks heaps! worked really well!

**Comment by TheUnknownCod3r** [comment]
> > Completed in latest push
> 
> Thanks heaps! worked really well!

No worries! Anything else you consider, let me know! I've got a few things up my sleeve, now I know a bit more about the game, and the way things are done.
